
export const offerTableDatas = [
  {
    key: '1',
    shopName: 'Shop 01',
    itemName: 'Burger',
    offerType: 'Flat Discount',
    category: 'Burger',
    startDate: '2025-02-05',
    endDate: '2025-02-05',
    price: 250.0,
    status: 'pending',
  },
  {
    key: '2',
    shopName: 'Shop 01',
    itemName: 'Burger',
    offerType: 'Flat Discount',
    category: 'Burger',
    startDate: '2025-02-05',
    endDate: '2025-02-05',
    price: 250.0,
    status: 'pending',
  },
  {
    key: '3',
    shopName: 'Shop 01',
    itemName: 'Burger',
    offerType: 'Flat Discount',
    category: 'Burger',
    startDate: '2025-02-05',
    endDate: '2025-02-05',
    price: 250.0,
    status: 'pending',
  },
  {
    key: '4',
    shopName: 'Shop 01',
    itemName: 'Burger',
    offerType: 'Flat Discount',
    category: 'Burger',
    startDate: '2025-02-05',
    endDate: '2025-02-05',
    price: 250.0,
    status: 'pending',
  },
  {
    key: '5',
    shopName: 'Shop 01',
    itemName: 'Burger',
    offerType: 'Flat Discount',
    category: 'Burger',
    startDate: '2025-02-05',
    endDate: '2025-02-05',
    price: 250.0,
    status: 'pending',
  },
];