
export const orderTableDatas = [
  {
    key: '1',
    date: '2025-02-05',
    image:"/orderProduct.jpg",
    orderNumber: 'ORD123456',
    userName: 'John Brown',
    location: 'New York, USA',
    offer: 'Black Friday Deal',
    orderItem: { name: 'Smart Watch', qty: 1 },
    price: 250.0,
    serviceCharge: 15.0,
    status: 'Delivered',
  },
  {
    key: '2',
    date: '2025-02-06',
    image:"/orderProduct.jpg",
    orderNumber: 'ORD654321',
    userName: 'Jane Green',
    location: 'London, UK',
    offer: 'Holiday Discount',
    orderItem: { name: 'Phone Case', qty: 2 },
    price: 50.0,
    serviceCharge: 5.0,
    status: 'Preparing',
  },
  {
    key: '3',
    date: '2025-02-06',
    image:"/orderProduct.jpg",
    orderNumber: 'ORD654321',
    userName: 'Jane Green',
    location: 'London, UK',
    offer: 'Holiday Discount',
    orderItem: { name: 'Phone Case', qty: 2 },
    price: 50.0,
    serviceCharge: 5.0,
    status: 'Ready for Pickup',
  },
  {
    key: '3',
    date: '2025-02-06',
    image:"/orderProduct.jpg",
    orderNumber: 'ORD654321',
    userName: 'Jane Green',
    location: 'London, UK',
    offer: 'No',
    orderItem: { name: 'Phone Case', qty: 2 },
    price: 50.0,
    serviceCharge: 5.0,
    status: 'Pending',
  },
];